version: "3"
services:
  ncservices:
    image: ncservices
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - .:/opt/ncservices

  worker:
    image: ncservices
    build: .
    command: celery -A ncservices.celery worker -l info --max-tasks-per-child=250 --max-memory-per-child=262144 --pool=gevent --concurrency=30
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - .:/opt/ncservices

  beat:
    image: ncservices
    build: .
    command: celery -A ncservices.celery beat -l info
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - .:/opt/ncservices

  mariadb:
    image: mariadb:10
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    depends_on:
      - mariadb
    ports:
      - 3380:8080

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - "1080:1080"

volumes:
  dbdata:
