version: "3"
services:
  ncservices:
    image: ncservices
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/opt/ncservices

  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 3380:80
    env_file:
      - .env

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - "1080:1080"
